version: '3'
services:
    mongodb:
        image: 'mongo:latest'
        container_name: mongodb-notas
        env_file:
            - .env
        ports:
            - '27017:27017'
        volumes:
            - ./back/db/mongodb_data_container:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        restart: always

    api:
        tty: true
        build:
            context: ./
            dockerfile: ./back/Dockerfile
        working_dir: /usr/src/app
        volumes:
            - ./back:/usr/src/app
            # - usr/src/app/node_modules
        ports:
            - '${API_PORT}:${API_PORT}'
        command: npm run start:dev
        env_file:
            - .env
        depends_on:
            - mongodb

    front:
        tty: true
        build:
            context: .
            dockerfile: ./front/Dockerfile
        working_dir: /usr/src/app
        volumes:
            - ./front:/usr/src/app
        ports:
            - '${FRONT_PORT}:${FRONT_PORT}'
        env_file:
            - .env
        depends_on:
            - api

volumes:
    mongodb_data_container:
